name: Marketplace Release

on:
    push:
        tags:
            - "*-web-v*"
            - "*-native-v*"
            - "*-hybrid-v*"

jobs:
    publish_release:
        name: "Marketplace Release"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@v2
              with:
                  submodules: false
            - name: "Defining cache"
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            - name: "Defining Environment Variables"
              id: variables
              run: echo "::set-output name=tag::$(git tag --points-at HEAD)"
            - name: "Installing dependencies"
              run: npm install
            - name: "Build and publish pluggale widget ${{ steps.variables.outputs.tag }}"
              run:
                  "npm run build"
            - name: "Release MPK Files"
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "${{ steps.variables.outputs.tag }}"
                  prerelease: false
                  title: "MPK Files"
                  files: |
                      dist/*.mpk
